### ISSUE TITLE
base_url error with terraform plan

### ISSUE THREAD

**Issue by monteago30** [core-infra-svcs/terraform-provider-meraki#240]
provider "meraki" {
base_url = "https://api.meraki.com/api/v1"
}

Error: Invalid Attribute Value Match
│ 
│   with provider["registry.terraform.io/core-infra-svcs/meraki"],
│   on main.tf line 12, in provider "meraki":
│   12:   base_url = "https://api.meraki.com/api/v1"
│ 
│ Attribute base_url The API version must be specified in the URL. Example: https://api.meraki.com, got: https://api.meraki.com/api/v1

**Comment by andreassb** [comment]
The existing regex validator is ^(https:\/\/)(?:[a-zA-Z0-9]{1,62}(?:[-\.][a-zA-Z0-9]{1,62})+)(:\d+)?$
This does **not** math any of these:

- Examples provided in the provider documentation: https://api.meraki.com/v1 and https://api.meraki.cn/v1
- Base URLs as defined by Cisco in the Meraki documentation: https://api.meraki.com/api/v1 and https://api.meraki.cn/api/v1
- URL provided in error message: https://api.meraki.com

**Comment by iamdexterpark** [comment]
Thanks for raising this issue!

As mentioned by @andreasbaekdahl, the workaround is to omit the base_url. I'll look at this issue after #241 

I've also noticed that if this is set, one of my data source API endpoints returns an unexpected response. 
<img width="1236" alt="http-resp" src="https://github.com/core-infra-svcs/terraform-provider-meraki/assets/30270784/c8b9e119-307d-4c8f-8c51-fb85f524917b">

**Comment by iamdexterpark** [comment]
WIP: #245

**Comment by iamdexterpark** [comment]
Thank you for your PR. I can confirm that as of v0.6.3, this issue is resolved. You can use both/either/none of:

base_url = "https://api.meraki.com"
base_path = "/api/v1"

Thanks for raising this issue and making the provider even better!
