### ISSUE TITLE
beacon_id_params in meraki_devices resource causing Value Conversion Error

### ISSUE THREAD

**Issue by kikumar552** [core-infra-svcs/terraform-provider-meraki#247]
Error: Value Conversion Error
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│
│ Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
│
│ Path: beacon_id_params
│ Target Type: provider.DevicesResourceModelBeaconIdParams
│ Suggested `types` Type: basetypes.ObjectValue
│ Suggested Pointer Type: *provider.DevicesResourceModelBeaconIdParams

**Comment by jamesbrink** [comment]
This has been a big blocker for me as well.
