### ISSUE TITLE
Release that includes wireless network resource

### ISSUE THREAD

**Issue by arjenvri** [core-infra-svcs/terraform-provider-meraki#258]
would it be possible to have a new release that includes the new wireless settings resource?

thank you for providing this very useful provider for meraki dashboard management!

**Comment by iamdexterpark** [comment]
Release 0.6.0 is now available with SSIDS resource: https://registry.terraform.io/providers/core-infra-svcs/meraki/latest/docs/resources/networks_wireless_ssids
