### ISSUE TITLE
Rename imported network resource error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by lairdnet** [core-infra-svcs/terraform-provider-meraki#260]
Import of existing network is successful but subsequent change to network name results in error (replaced ids): 

Error: Provider produced inconsistent result after apply
When applying changes to meraki_network.test2, provider "provider[\"registry.terraform.io/core-infra-svcs/meraki\"]" produced an unexpected new value: .url: was cty.StringVal("https://n000.meraki.com/lab-network-manu/n/abcdefg0/manage/usage/list"), but now cty.StringVal("https://n000.meraki.com/lab-network-chan/n/abcdefg0/manage/usage/list").

This is a bug in the provider, which should be reported in the provider's own issue tracker.

Terraform resources, network name was originally "lab-network-manual-1" (replaced ids):

import {
  to = meraki_network.test2
  id = "0000000,L_00000000000000000"
}

resource "meraki_network" "test2" {
    product_types = [ "appliance", "switch", "wireless", "camera", "sensor", "cellularGateway" ]
    name = "lab-network-changed-2"
}

**Comment by iamdexterpark** [comment]
Hello @lairdnet ,

We recently released v0.6.0, which includes refactor to the network import. Can you upgrade to this version and please try again? 

Thanks in advacne!

**Comment by lairdnet** [comment]
@iamdexterpark , confirmed that resolved the issue with renaming an existing network. Thanks for the quick turnaround.
