### ISSUE TITLE
ssid import error:  number field causing Int64 Type Validation Error

### ISSUE THREAD

**Issue by kikumar552** [core-infra-svcs/terraform-provider-meraki#291]
number field causing Int64 Type Validation Error while trying to import the ssid

Error: Int64 Type Validation Error
│
│ An unexpected error was encountered trying to validate an attribute value. This is always an error in the provider. Please report the following to the provider developer:
│
│ Expected Number value, received tftypes.Value with value: tftypes.String<"0">

**Comment by iamdexterpark** [comment]
resolved with v0.10.2
