### ISSUE TITLE
Example configuration with "base_url" causes failures

### ISSUE THREAD

**Issue by crvatwork** [core-infra-svcs/terraform-provider-meraki#313]
There are a couple things going on here that seem to be intermingled and problematic. When setting `base_url` per the existing [example configuration](https://github.com/core-infra-svcs/terraform-provider-meraki/blob/main/README.md#configuration) as `base_url = "https://api.meraki.com"` running `terraform apply` gives a 404 error. When adding `base_path = "/api/v1"` then the error message will switch to a 403.

It seems like the culprit is a double "/" included in the URL, which looks like it was at least partially introduced [in this commit](https://github.com/core-infra-svcs/terraform-provider-meraki/commit/b369860b1ca352b6834bffaec3b785c68e5a041f). I was sanity checking my api key and calls via Postman and verified that a double "/" results in a 403 from the Meraki API.

Interestingly if `base_url` is removed entirely from the provider configuration everything seems to work just fine (regardless of the presence of `base_path`). I also don't see https://api.meraki.com anywhere in the source so I'm really confused as to where it's getting that as a default value.

I've attached the .tf files and a debug log for both the 404 and 403 errors. 
[base_url_and_base_path.zip](https://github.com/core-infra-svcs/terraform-provider-meraki/files/14579466/base_url_and_base_path.zip)
[base_url_only.zip](https://github.com/core-infra-svcs/terraform-provider-meraki/files/14579468/base_url_only.zip)

**Comment by iamdexterpark** [comment]
Thank you for your PR. I can confirm that as of v0.6.3, this issue is resolved. You can use both/either/none of:

base_url = "https://api.meraki.com"
base_path = "/api/v1"

Thanks for rasing this issue and making the provider even better!
